wmde/wikit

Dockerfile
README.md
docker-compose.yml

Use `docker` and `docker-compose` to ease creating a level playing field for development as already seen in some other projects. Uses latest npm.

add docker-based infrastructure

---

.gitignore
README.md
package-lock.json
package.json

The repository root will become the top layer of a lerna project.
We want to build CI first, so add a basic npm layer to be run there.

add npm root package

---

.github/workflows/test.yaml

Setup CI with GitHub Workflows following https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions

Add test workflow for CI

---

Dockerfile
README.md
lerna.json
package-lock.json
package.json
tokens/README.md
tokens/package.json
vue-components/README.md
vue-components/package.json

This adds the two packages `tokens` and `vue-components`, and models
the dependency between the two.

Add initial lerna setup

---

.editorconfig
tokens/.editorconfig
tokens/.eslintrc.js
tokens/.eslintrc.json
tokens/.gitignore
tokens/.style-dictionary/config.json
tokens/build/wikimedia-ui-base/index.js
tokens/build/wikimedia-ui-base/lib.js
tokens/package-lock.json
tokens/package.json
tokens/properties/global.json
tokens/tests/unit.js

This implements the first part of https://github.com/wmde/wikit-css/pull/22
Bug: https://phabricator.wikimedia.org/T255423

tokens: add style-dictionary and way to get global tokens

---

docs/adr/0001-use-a-design-system.md
docs/adr/0002-wikimedia-ui-base-variable-reuse.md
docs/adr/0003-agnostic-tokens.md
docs/adr/0004-monorepo.md
docs/adr/NNNN-adr-template.md

Clean up ADRs

---

docs/src/01-colors.stories.mdx
tokens/properties/global.json

A "color-interaction" category is introduced to group hover colors and the loner purple (color of visited links).

restructure global tokens

---

docs/src/lib/flattenTokenTree.js
tokens/.style-dictionary/config.js
tokens/.style-dictionary/lib.js
tokens/tests/getReferencedTokens.spec.js

https://github.com/wmde/wikit-css/pull/24 but with tests and actually using it in storybook
Bug: [T256022](https://phabricator.wikimedia.org/T256022)

Add list of referenced tokens to json build

---

tokens/.style-dictionary/lib.js
tokens/package-lock.json
tokens/package.json

See https://www.npmjs.com/package/string.prototype.matchall
Bug: [T256022](https://phabricator.wikimedia.org/T256022)

tokens: use matchall shim to ease source token identification

---

docs/src/06-font-weight.stories.mdx

Bug: [T256852](https://phabricator.wikimedia.org/T256852)

Add font-weight token demo

---

docs/src/07-z-index.stories.mdx

Bug: [T256860](https://phabricator.wikimedia.org/T256860)

docs: illustrate z-indexes

---

docs/src/08-transition.stories.mdx
docs/src/styles/transition.css

Bug: [T256859](https://phabricator.wikimedia.org/T256859)

docs: illustrate transitions

---

docs/src/lib/TokenTable.jsx

Dabbling to demonstrate a possible solution.
Of course, should be applied to all token pages alike if it makes sense.

docs: use link icon to illustrate anchor capability

---

docs/src/dummy.stories.js
docs/src/index.stories.js

This should appease chromatic which warns us if there are 0 stories it
can detect (does not care for mdx).
Bug: [T256864](https://phabricator.wikimedia.org/T256864)

docs: add one JS-based story

---

.github/workflows/chromatic.yaml
docs/.storybook/main.js
docs/package-lock.json
docs/package.json
docs/src/dummy.stories.js
docs/src/index.stories.js
package.json

Login with your GitHub account and you'll be able to see the wmde/wikit Builds
https://www.chromatic.com/builds?appId=5efdb3b5f65950002286285d

Use Chromatic with Storybook

---

docs/src/12-shadows.stories.mdx

Bug: [T256858](https://phabricator.wikimedia.org/T256858)

Add box-shadow page to Storybook

---

docs/src/09-break-points.stories.mdx

Bug: [T256856](https://phabricator.wikimedia.org/T256856)

docs: add break-points

---

docs/src/10-font-line-height.stories.mdx
docs/src/styles/line-height.css

Bug: [T256855](https://phabricator.wikimedia.org/T256855)

docs: add line-heights

---

docs/src/11-dimension.stories.mdx

Bug: [T256854](https://phabricator.wikimedia.org/T256854)

docs: add dimensions

---

docs/src/lib/presenters/Shadows.jsx
docs/src/styles/shadows.css

Style changes are based on feedback from UX provided in [T256858](https://phabricator.wikimedia.org/T256858#6277435)

Improve shadow tokens visualization

---

docs/src/styles/transition.css

Bug: [T256859](https://phabricator.wikimedia.org/T256859)

docs: change transition style per UX recommendation

---

docs/.eslintrc.json
docs/src/dummy.stories.js
tokens/.eslintrc.json

This was discussed in https://github.com/wmde/wikit/pull/16/ and
suggests on of the two mentioned approaches.
See https://eslint.org/docs/rules/func-style#declaration

linting: prefer declaration style of function definition

---

docs/src/lib/TokenPresenter.jsx
docs/src/lib/presenters/BorderColor.jsx

Improvements related to https://phabricator.wikimedia.org/T257057#6285220

Color the border, not the background for border-color tokens

---

docs/src/lib/presenters/LineHeight.css
docs/src/lib/presenters/LineHeight.jsx

Improvements made are based on feedback provided by UX here [T256855](https://phabricator.wikimedia.org/T256855#6277459)

Improve line height storybook page

---

docs/README.md
tokens/README.md

Bug: [T256024](https://phabricator.wikimedia.org/T256024)

document connection between tokens and docs

---

docs/src/04-background-color.stories.mdx
docs/src/05-border-color.stories.mdx
docs/src/08-box-shadows.stories.mdx
docs/src/lib/TokenTable.jsx
docs/src/styles/token-table.css

Addresses the points 1 and 3 from https://phabricator.wikimedia.org/T256024#6300489
Point 2 (not addressed here) is mildly scary and I created https://phabricator.wikimedia.org/T257805 for it.

Ux followups

---

tokens/properties/alias.json
tokens/properties/global.json

Applying some improvements detected while creating button specs

Token updates

---

docs/src/doc/dev/adr/0005-use-typescript.stories.mdx

[T257813](https://phabricator.wikimedia.org/T257813)

Add ADR for using TypeScript without Decorators

---

tokens/properties/alias.json
tokens/properties/global.json

Formatted to look the way my IDE thinks is best using the "reformat code" action.

Consistently format token json files

---

docs/src/doc/dev/adr/0006-manual-token-doc.stories.mdx
docs/src/doc/dev/adr/NNNN-adr-template.mdx

Bug: [T258246](https://phabricator.wikimedia.org/T258246)

ADR about manual token documentation

---

vue-components/.browserslistrc

The list was compiled based on
https://github.com/browserslist/browserslist#full-list
and
https://www.mediawiki.org/wiki/Compatibility#Browser_support_matrix

Configure browserslist

---

docs/src/doc/dev/adr/0007-css-base.stories.mdx

Bug: https://phabricator.wikimedia.org/T257828

docs: document base CSS decision

---

vue-components/package-lock.json
vue-components/package.json
vue-components/postcss.config.js

Using [postcss-prefixwrap](https://github.com/dbtedman/postcss-prefixwrap)

Create a shared style namespace

---

vue-components/.storybook/main.js
vue-components/.storybook/preview.js
vue-components/package-lock.json
vue-components/package.json
vue-components/stories/HelloWorld.stories.js

Add addon-knobs and addon-a11y and configure our dummy story to expose a
knob.
Bug: https://phabricator.wikimedia.org/T257824

vue-components: storybook: update & add addons

---

vue-components/.eslintrc.js
vue-components/.storybook/webpack.config.js
vue-components/jest.config.js
vue-components/src/styles/main.scss
vue-components/tests/config/JestCustomEnvironment.js
vue-components/tests/config/setup.ts
vue-components/vue.config.js

Adds some more prerequisites for the development of components and their tests.
Bug: https://phabricator.wikimedia.org/T257812

vue-components: prerequisites

---

tokens/properties/components/Button.json
vue-components/src/components/Button.vue
vue-components/src/main.ts
vue-components/stories/Button.stories.js
vue-components/tests/unit/components/Button.spec.ts

Please review/merge #122 first.
Bug: https://phabricator.wikimedia.org/T256779

vue-components: implement neutral flavor of Button

---

vue-components/tests/e2e/specs/Button.test.js

This PR should go in before #123.

Browser Tests: test the button, not the dummy

---

tokens/properties/components/Button.json
vue-components/src/components/Button.vue
vue-components/stories/Button.stories.ts
vue-components/tests/unit/components/Button.spec.ts

This PR adds the primary progressive flavor to the Button component.

vue-components: Add primaryProgressive Button flavor

---

tokens/properties/components/Button.json
vue-components/src/components/Button.vue
vue-components/stories/Button.stories.ts

Please review/merge #128 first.

vue-components: Add button type destructive

---

docs/package-lock.json
docs/package.json
docs/src/dummy.stories.js
package.json
vue-components/package-lock.json
vue-components/package.json
vue-components/tests/e2e/custom-commands/openComponentStory.js

Please review/merge #141 first.
Since we run Chromatic only on the vue storybook, there's no need of a dummy component in the docs one.

Remove dummy component from docs storybook

---

docs/src/doc/create-reusable-components/03_developing_components.stories.mdx
vue-components/src/components/Button.vue

https://phabricator.wikimedia.org/T260117

Document component level token naming conventions

---

docs/src/doc/01_getting_started.stories.mdx
docs/src/doc/create-reusable-components/03_developing_components.stories.mdx
docs/src/doc/decisions-and-ADRs/01_overview.stories.mdx

docs: Update dev docs

---

docs/src/doc/create-reusable-components/01_overview.stories.mdx

Created an introductory text for 01_overview.stories.mdx

---

docs/.storybook/manager.js
docs/.storybook/wikit.js
docs/package-lock.json
docs/package.json
docs/src/00-doc/01_getting_started.stories.mdx
docs/src/00-doc/03-create-reusable-components/01_overview.stories.mdx
docs/src/00-doc/03-create-reusable-components/03_developing_components.stories.mdx
docs/src/00-doc/05-decisions-and-ADRs/01_overview.stories.mdx
docs/src/00-doc/05-decisions-and-ADRs/adr/0003-agnostic-tokens.stories.mdx
docs/src/00-doc/05-decisions-and-ADRs/adr/0004-monorepo.stories.mdx
docs/src/00-doc/05-decisions-and-ADRs/adr/0005-use-typescript.stories.mdx
docs/src/00-doc/05-decisions-and-ADRs/adr/0008-css-scoping.stories.mdx

This PR:
- Adds table of contents to several main pages including "Getting Started"
- Fixes missing links and broken emojis in ADRs
- Changes the Storybook logo

docs: Various improvements

---

docs/package-lock.json
docs/package.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

Bump version to 1.0.1

---

README.md

We have a new Saucelabs account to use for our CI.
I already changed the env variables for the browser tests in `Settings/Secrets`

Change saucelabs badges because of  new username

---

tokens/properties/components/TextInput.json
vue-components/src/components/Button.vue
vue-components/src/components/TextInput.vue
vue-components/src/main.ts
vue-components/stories/TextInput.stories.ts
vue-components/tests/unit/components/TextInput.spec.ts

Phabricator task: https://phabricator.wikimedia.org/T263734
Figma spec: https://www.figma.com/file/gi3JYwSUQYhKS0mHwK25cQwi/WiKit?node-id=3975%3A1
Most of the code here was written in pair programming by @guergana and @jakobw.

vue-components: create TextInput component

---

vue-components/src/components/TextInput.vue
vue-components/tests/unit/.eslintrc.js
vue-components/tests/unit/components/TextInput.spec.ts

This is necessary in order to get the user input out of that component,
and bind it e.g. via v-model:
https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components

TextInput: emit input event on user input

---

README.md
docs/src/00-doc/03-create-reusable-components/03_developing_components.stories.mdx
docs/src/00-doc/04_release_management.stories.mdx

+ added in README
+ added in storybook

docs for version release using lerna version

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

Contains fixes for type declarations that caused problems for consuming applications at build time.

Prepare v1.1.1 release

---

tokens/properties/alias.json

Corrected the value of the token _background-color-feedback-notice_, which should be _base 80_ instead of _base 90_.

correct wrong bg color value

---

tokens/properties/components/TextInput.json
tokens/properties/components/ValidationMessage.json
vue-components/src/components/TextInput.vue
vue-components/src/components/ValidationMessage.vue
vue-components/stories/Input.stories.ts
vue-components/stories/ValidationMessage.stories.ts
vue-components/tests/unit/components/TextInput.spec.ts
vue-components/tests/unit/components/ValidationMessage.spec.ts

Similar to #209 but for the `FeedbackMessage` component.
Bug: [T265005](https://phabricator.wikimedia.org/T265005)

vue-components: extract ValidationMessage sub component from TextInput

---

vue-components/package-lock.json

This was created with the help of lerna-audit and manually reverting the
changes created to the package.json[1].
This was cherry-picked [from the lerna-audit branch](https://github.com/wmde/wikit/commits/lerna-audit) as I don't think it makes sense to add it to the repo while that is still behaving in a weird fashion.
[1]: https://github.com/tnobody/lerna-audit/issues/15

vue-components: npm audit fix

---

tokens/properties/components/Icon.json
vue-components/src/components/Icon.vue
vue-components/src/components/iconProps.ts
vue-components/stories/Icon.stories.ts

Bug: [T265582](https://phabricator.wikimedia.org/T265582)

Add icons for success/checkmark and notice/info

---

vue-components/nightwatch.config.js
vue-components/tests/e2e/specs/Lookup.test.js

created browser tests that check if
+ the menu appears on user input
+ no matches found text is displayed
+ selection indicator text is visible after selecting menu-item
What's not included:
+ test of the keyboard navigation. This could be added once as a separate ticket once the keyboard navigation task is completed.

Lookup browser test

---

vue-components/src/components/LookupMenu.vue

Typecast HTML element to remedy current type errors on master

Typecast html elems

---

vue-components/src/components/LookupMenu.vue
vue-components/stories/Lookup.stories.ts

This PR has two commits:
+ fix a display error of the menuItem to be above the elements below.
+ Error and Warning states added to main Lookup component Story
T266595

Add story for Lookup with error state and warning state

---

tokens/properties/components/Input.json
vue-components/package-lock.json
vue-components/src/components/Input.vue

Quick fix to apply a white background color to the Input component and prevent transparency. The issue remained unnoticed during component verfication.

define input bg color

---

vue-components/package-lock.json
vue-components/package.json
vue-components/src/components/Lookup.vue
vue-components/src/components/LookupMenu.vue
vue-components/tests/unit/components/Lookup.spec.ts

Keyboard navigation for selecting an item

---

vue-components/src/main.ts

It's not really usable without it

Expose Message component

---

docs/src/00-doc/03-create-reusable-components/03_developing_components.stories.mdx

Noticed a couple of issues with this docs file

Fix minor issues with documentation

---

vue-components/src/components/Lookup.vue
vue-components/src/components/LookupMenu.vue
vue-components/tests/unit/components/Lookup.spec.ts

Refactor keyboard handling into LookupMenu

---

CHANGELOG.md
tokens/package-lock.json
tokens/package.json
tokens/properties/alias.json
tokens/properties/global.json

A couple of new tokens were introduced in order to align our styles with wikimedia-ui-base. No values were modified in this update.
Issue: https://phabricator.wikimedia.org/T268032

uptade wikimedia-ui-base dependency to v0.18

---

tokens/package-lock.json
tokens/package.json

```bash
+ eslint@7.13.0
updated 1 package and audited 812 packages in 4.792s
```

tokens: Update dependencies

---

docs/package-lock.json

Running `npm install` in the `/docs` package generates changes in `package-lock.json`

docs: Update package-lock

---

.gitignore

When I use IntelliJ, this is being added and causes annoyance.

Add *.iml to .gitignore

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

We need the new version in query builder, it's currently blocking lots
of work.

Bump version to 2.0.0-alpha.0

---

tokens/properties/components/OptionsMenu.json
vue-components/src/components/Lookup.vue
vue-components/src/components/OptionsMenu.vue
vue-components/stories/OptionsMenu.stories.ts
vue-components/tests/unit/components/Lookup.spec.ts

Builds upon: #284 
Is followed by: #244 
They should not just be treated as if they hovered with the keyboard,
but they have their own dedicated style and behavior.

Correct styles for selected items

---

CHANGELOG.md
vue-components/src/components/Icon.vue
vue-components/src/components/iconProps.ts
vue-components/tests/unit/components/Icon.spec.ts
vue-components/tests/unit/components/__snapshots__/Icon.spec.ts.snap

Bug: [T268843](https://phabricator.wikimedia.org/T268843)

vue-components: add "clear" Icon type

---

CHANGELOG.md
vue-components/src/components/Icon.vue
vue-components/src/components/iconProps.ts
vue-components/tests/unit/components/Icon.spec.ts
vue-components/tests/unit/components/__snapshots__/Icon.spec.ts.snap

Add new icon "edit" icon

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

Start a new pre-release: 2.0.0-alpha.1

---

docs/src/00-doc/03-create-reusable-components/02_designing_components.stories.mdx

This aims at improving and completing the _Designing components_ documentation. It also contains a small fix applied to the dev documentation.

Fix documentation

---

vue-components/src/components/Button.vue
vue-components/stories/Button.stories.ts

added iconOnly prop that sets different internal padding to the button when iconOnly prop is given

Allow buttons to take iconOnly prop

---

vue-components/stories/Button.stories.ts
vue-components/stories/QuietButton.stories.ts

+ quiet text only
+ quiet icon only

added button quiet subpages

---

vue-components/stories/Button.stories.ts
vue-components/stories/QuietButton.stories.ts

Also, we are being a good role-model by using it ourselves.
Bug: [T269140](https://phabricator.wikimedia.org/T269140)

Add information about using aria-label to icon only buttons

---

CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

Add checkbox component, also adding it to CHANGELOG

Add a new pre-release (2.0.0-alpha.3)

---

vue-components/src/main.ts

Add Checkbox component to list of vue-components

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

New pre-release (2.0.0-alpha.4)

---

vue-components/src/components/Dropdown.vue
vue-components/src/components/OptionsMenu.vue
vue-components/tests/unit/components/Dropdown.spec.ts

[T268771](https://phabricator.wikimedia.org/T268771)

Allow looping within options menu via keyboard

---

vue-components/src/components/Dropdown.vue
vue-components/src/components/OptionsMenu.vue
vue-components/tests/unit/components/Dropdown.spec.ts
vue-components/tests/unit/components/Lookup.spec.ts

naviagting lookup menu using keyboard
Bug: T267829

Added scroll functionality when naviagting lookup menu using keyboard

---

CHANGELOG.md
vue-components/src/components/Icon.vue
vue-components/src/components/iconProps.ts

Bug: [T273652](https://phabricator.wikimedia.org/T273652).

Add new icon for additions

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

To have the new icon types, needed for T272887

New pre-release: 2.0.0-alpha.6

---

vue-components/src/components/ExtendedNumberInput.vue
vue-components/src/components/util/validateExtendedNumberInput.ts
vue-components/src/main.ts
vue-components/stories/ExtendedNumberInput.stories.ts
vue-components/tests/unit/components/ExtendedNumberInput.spec.ts
vue-components/tests/unit/components/util/validateExtendedNumberInput.spec.ts

Introduce ExtendedNumberInput component

---

vue-components/src/components/Popover.vue
vue-components/src/components/PopoverProps.ts
vue-components/stories/Popover.stories.ts
vue-components/tests/unit/components/Popover.spec.ts

Bug: T274259
TODO:
@micgro42 whenever you've time, can you look over this PR? I would appreciate some feedbacks on this.

position_the_popover_based_on_a_prop

---

vue-components/src/components/Lookup.vue
vue-components/src/components/LookupCore.vue
vue-components/src/components/LookupInput.vue
vue-components/tests/e2e/specs/Lookup.test.js
vue-components/tests/unit/components/Lookup.spec.ts
vue-components/tests/unit/components/LookupCore.spec.ts

We'll need that core in the QuantityInput component.

refactor: extract core of LookupComponent

---

CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
tokens/properties/components/Link.json
vue-components/package-lock.json
vue-components/package.json
vue-components/src/components/Button.vue
vue-components/src/components/ExtendedNumberInput.vue
vue-components/src/components/Icon.vue
vue-components/src/components/Link.vue
vue-components/src/components/OptionsMenu.vue
vue-components/src/components/ToggleButton.vue
vue-components/src/components/iconProps.ts
vue-components/src/components/util/validateExtendedNumberInput.ts
vue-components/src/main.ts
vue-components/src/styles/main.scss
vue-components/src/styles/mixins/Link.scss
vue-components/stories/Dropdown.stories.ts
vue-components/stories/ExtendedNumberInput.stories.ts
vue-components/stories/Icon.stories.ts
vue-components/stories/Link.stories.ts
vue-components/tests/unit/components/Dropdown.spec.ts
vue-components/tests/unit/components/ExtendedNumberInput.spec.ts
vue-components/tests/unit/components/Lookup.spec.ts
vue-components/tests/unit/components/util/validateExtendedNumberInput.spec.ts

Issue: [T272958](https://phabricator.wikimedia.org/T272958)

Link component

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

This brings link component and popover component

New pre-release: 2.0.0-alpha.7

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

- Bug fix for icons being used multiple times #389
- Add named slot for tooltip #386

New Pre-release: 2.0.0-alpha.8

---

CHANGELOG.md
vue-components/src/main.ts

Bug fix: QuantityInput component needs to be exported to be consumed in the QB

Export QuantityInput Component

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

new pre-release
bump version to 2.0.0-alpha.9

bump version

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

Add new pre-release 2.0.0-alpha.11

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

Add new pre-release: 2.0.0-alpha.12

---

tokens/properties/mixins/Label.json
vue-components/src/components/Checkbox.vue
vue-components/src/components/Dropdown.vue
vue-components/src/components/ExtendedNumberInput.vue
vue-components/src/components/InputWithExtender.vue
vue-components/src/components/Lookup.vue
vue-components/src/components/QuantityInput.vue
vue-components/src/components/TextInput.vue
vue-components/src/styles/mixins/Label.scss

Note that "disabled" attribute doesn't work on <label> so it needs
class.
Bug: T268842

Disabled components should display disabled labels

---

vue-components/src/components/Dropdown.vue

Issue: [T275052](https://phabricator.wikimedia.org/T275052)

Remove unnecessary outline of dropdowns in Safari

---

vue-components/package-lock.json
vue-components/package.json
vue-components/src/components/Popover.vue
vue-components/stories/Popover.stories.ts

See the individual commit messages for details.
Bug: [T274261](https://phabricator.wikimedia.org/T274261)

Check for overflow in Popover

---

vue-components/src/components/Popover.vue
vue-components/tests/unit/components/Popover.spec.ts

Bug: [T277738](https://phabricator.wikimedia.org/T277738)

Add keyboard navigation handlers for popover component

---

.github/workflows/test-and-demo.yaml

The repository owner is wmde, not wikit.

Fix repository owner comparison in CI

---

CHANGELOG.md
tokens/package-lock.json
tokens/package.json

Update wikimedia base UI from 0.18.0 to 0.19.0

Update wikimedia base UI

---

tokens/properties/components/Message.json

Issue: [T268486](https://phabricator.wikimedia.org/T268486)

Remove Message's border-radius

---

docs/src/00-doc/04_release_management.stories.mdx

While creating my first pre-release I ran into a few issues and found learnings as documented here.

Document learnings from creating a pre-release

---

.github/workflows/comment-deploy-url-to-pr.yaml

Fix hash in building the comment of netlify app

---

vue-components/src/components/TextArea.vue
vue-components/stories/TextArea.stories.ts

Two missing fixes:
- The TextArea story file was missing a comma (for sure this is collateral damage from conflict solving), and tests kept complaining
- A calc needed to be introduced to adjust the min-height of the text area

TextArea fixes

---

vue-components/src/components/Breakpoint.ts
vue-components/src/components/Table.vue
vue-components/tests/unit/components/Table.spec.ts

Table component with basic states from Mismatch Finder. Task [T289843](https://phabricator.wikimedia.org/T289843)
Bug: [T291074](https://phabricator.wikimedia.org/T291074)

Move basic Table Component from Mismatch Finder to Wikit

---

.github/workflows/test-and-demo.yaml

The build step is invoked in case of a cache hit.
https://phabricator.wikimedia.org/T290426

Add a Build step to the setup job of the Test and Deploy workflow

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

Pre-release version 2.1.0-alpha.7

Bump version to v2.1.0-alpha.7

---

CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

Bug: [T298186](https://phabricator.wikimedia.org/T298186)

Bump version to 2.1.0-alpha.10

---

.github/workflows/test-and-demo.yaml

Run CI also for next branch

---

vue-components/src/styles/main.scss
vue-components/src/styles/mixins/Typography.scss

* Create Typography mixins
* Add newline at end of Typography.scss file

Cherry-pick "Create Typography mixins (#486)"

---

docs/.storybook/main.js
docs/package-lock.json
docs/package.json
docs/src/mixins/01-typography.scss
docs/src/mixins/01-typography.stories.mdx
tokens/properties/alias.json
vue-components/src/styles/main.scss
vue-components/src/styles/mixins/Typography.scss

⚠️ Should be merged after #486

Mixins proof of concept

---

vue-components/package-lock.json
vue-components/package.json

After #536 merged, this is now comfortably simple.

Upgrade TypeScipt to 4.5

---

vue-components/nightwatch.config.js
vue-components/package-lock.json
vue-components/package.json
vue-components/tests/e2e/specs/Lookup.test.js

This is done in preparation of upgrading vue-cli to version 5 in #548 which also upgrades the vue-cli internal version of nightwatch to version 2.
Bug: T301155

Upgrade nightwatch and fix some deprecated assertions

---

vue-components/src/components/Message.vue
vue-components/src/main.ts
vue-components/stories/Message.stories.ts
vue-components/tests/a11y/AllComponents.spec.ts
vue-components/tests/unit/components/Message.spec.ts

That Message component was deleted in #534, but we do in fact need it in the current project. So this PR adds it back. 
To make review easier, the first commit just plain copies the files from the master branch without any changes, and the second commit makes the adjustments that are needed for Vue3.

Readd Message component to next branch

---

vue-components/src/components/Icon.vue
vue-components/tests/unit/components/__snapshots__/Icon.spec.ts.snap

* add aria-hidden attribute to decorative svg icons
* add focusable=false for IE so that svg icons are decalared decorative
* add html attributes directly to the icon component and adjust tests

Cherry Pick "Update a11y message component (#575)"

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

`npm run bump-version -- prerelease`
Bug: T304511

Bump version to 3.0.0-alpha.3

---

vue-components/src/components/Lookup.vue
vue-components/src/components/LookupInput.vue
vue-components/stories/Lookup.stories.ts

.sync is Vue 2 syntax; in Vue 3, use [multiple v-model bindings][1].
[1]: https://vuejs.org/guide/components/events.html#multiple-v-model-bindings

Don’t use .sync for Lookup stories

---

vue-components/src/main.ts

This was forgotten in #597
We really should have some test for this :/.

Export Link component in order to make it actually available

---

vue-components/tests/e2e/specs/Dialog.test.js

Similar to how the Lookup tests wait for the Lookup to be present.

Wait for Button to be present in Dialog e2e tests

---

package-lock.json
package.json

This resolves several npm audit issues in the root package-lock.json.

Update lerna to 5.2.0

---

vue-components/package-lock.json

Done by `npm -C vue-components/ audit fix`.

vue-components: update terser

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

`npm run bump-version prerelease`
Bug: T313891

Bump version to 3.0.0-alpha.7 (#596)

---

tokens/properties/alias.json
tokens/properties/components/Input.json
vue-components/src/components/Input.vue

Bug: [T312633](https://phabricator.wikimedia.org/T312633)

Display WiKit Input placeholder correct color

---

tokens/properties/alias.json
tokens/properties/components/Input.json
vue-components/src/components/Input.vue

Duplicating the placeholder color task for the master branch to be released in v2.x versions of Wikit
Bug: T312633

Display WiKit Input placeholder correct color for v2.x release

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

Bug: [T312633](https://phabricator.wikimedia.org/T312633)

Bump version to v2.1.0-alpha.13

---

vue-components/src/components/Lookup.vue
vue-components/tests/unit/components/Lookup.spec.ts

Let extra Lookup attributes fall trough to the <input>

---

vue-components/src/components/OptionsMenu.vue
vue-components/stories/Lookup.stories.ts

Bug: T324743
Co-authored-by: Michael Große <micgro42@users.noreply.github.com>

Fix Lookup menu navigation index reset issue on arrow down

---

CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

Changelog:
- Fix Lookup navigation on arrow down
Bug: T324743

Bump version to v.3.0.0-alpha.10

---

.github/workflows/comment-deploy-url-to-pr.yaml

Change set-output command to environment variable

---

CHANGELOG.md

Add backticks so 'input' is shown

Add backticks so 'input' is shown

---

docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

Bump version to v3.0.0-alpha.11

---

vue-components/src/components/OptionsMenu.vue

Fix Lookup component scrollbar height after open and closing menu

---

CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
tokens/package-lock.json
tokens/package.json
vue-components/package-lock.json
vue-components/package.json

Bump wikit version
