wmde/wikit

- package.json
This ensures that package-level deps (and all of lerna's magic) are
installed if npm is used to install (or ci) via npm.
This way around the setup is more in line with most of our other
projects (npm as the entrypoint) and it is also possible to use lerna
(after npm installation) without having lerna installed globally.
> root: run lerna bootstrap upon npm install

- tokens/properties/global.json
Uses a mixture of local values and values cherry-picked from the WMF.
We are trying to reuse as much as possible but ensure a structure we
deem consistent and add local values where there is nothing appropriate to cherry-pick. We will
recommend the delta for upstreaming.
Technically, this is the state as of [0] - the history did not contain
much information in the commit messages which made carrying it over not
worth it.
[0]: https://github.com/wmde/wikit-css/pull/22/commits/4387d23
Bug: https://phabricator.wikimedia.org/T255423
> tokens: set global tokens

- tokens/.eslintignore
Eslint ignores dot folders by default. We don't want that in this case.
> tokens: lint .style-dictionary folder, too

- docs/adr/wikimedia-ui-base-variable-reuse.md
I shied away from adding a number to this ADR, because I'm unsure whether we would move the "agnostic design system" ADR that currently sits in the `wikibase/vuejs-components` here first. I think it would fit here better. TBD!
> ADR: Approach for reuse of variables from wikimedia-ui-base

- .github/workflows/document.yaml
- docs/.gitignore
- docs/package.json
- package.json
This uses the gh-pages branch to host the built storybook.
It only excecutes on the master branch (I ran it w/o this filter to try)
and will need an overhaul when we want to host all the branches, but it
should give us results to demo now.
See
https://github.com/JamesIves/github-pages-deploy-action
https://wmde.github.io/wikit
> docs: publish the documentation on github pages

- docs/src/02-opacity.stories.mdx
Add thead & tbody to stop storybook from complaining (browser console):
```
Warning: validateDOMNesting(...): <tr> cannot appear as a child of
<table>. Add a <tbody>, <thead> or <tfoot> to your code to match the DOM
tree generated by the browser.
> docs: mark up opacity table correctly

- docs/src/03-cursors.stories.mdx
This
* shows the cursor tokens and values as a table
* illustrates the cursor upon hover of the value column
* renders ids and (self) links for the cursor tokens (not entirely sure where this is going yet)
* shows a lack of "source" token(s) as dash
Technically, this uses the token name to index the tr loop (key) - the
property is required by mdx, I assume to ensure that it can avoid
re-rendering things should the list change dyamically (like in Vue), and
the name is unique and stable by definition so lends itself better for
this use than the, by definition dynamic, index of the array.
We don't have that many representatives but there is a pattern emerging
e.g. between the cursors and the opacity story. Will look into how this
can be abstracted in a follow-up.
Bug: …
> docs: illustrate cursors

- docs/src/04-font-family.stories.mdx
Font family tokens illustrated, always with font size 16px as discussed with @SaiSan-WMDE in mattermost.
> Add font-family token demo

- docs/src/lib/TokenTable.jsx
This applies the default link styles and behavior from storybook to token links and prevents them from opening the story frame instead of navigating to the token anchor within the storybook.
> TokenTable: fix token links

- .github/workflows/chromatic.yaml
This is shown in every PR so naming it nicely makes sense.
Bug: [T256864](https://phabricator.wikimedia.org/T256864)
> chromatic: name build nicely

- docs/src/lib/TokenTable.jsx
Somewhat takes away from the semantics, but aligns those token pages visually 
and creates a bit more room for the presenters. Also somewhat explains to the
users the difference between primary values and values influenced by other
tokens.
Should probably recycle the very elements if we really mean to achieve
identical layout.
See
https://github.com/storybookjs/storybook/blob/b6136e1539c85d253504391a7d3f65e2c1239143/lib/components/src/blocks/ColorPalette.tsx#L170
> docs: align TokenTable with ColorPallete

- docs/src/lib/TokenTable.jsx
So that the deep links can be used to communicate between people.
Bug: [T256861](https://phabricator.wikimedia.org/T256861) (mentioned there)
There was a bug report of sorts in https://phabricator.wikimedia.org/T256861#6276737 and this hopefully solves it.
> docs: reflect clicked anchors in browser URL

- docs/src/01-colors.stories.mdx
- docs/src/04-font-family.stories.mdx
- docs/src/05-font-size.stories.mdx
- docs/src/06-font-weight.stories.mdx
- docs/src/07-line-height.stories.mdx
- docs/src/10-shadows.stories.mdx
- docs/src/11-transition.stories.mdx
- docs/src/12-cursors.stories.mdx
- docs/src/lib/TokenPresenter.jsx
- docs/src/lib/TokenTable.jsx
- docs/src/lib/presenters/Color.jsx
- docs/src/lib/presenters/Cursor.jsx
- docs/src/lib/presenters/Default.jsx
- docs/src/lib/presenters/FontFamily.jsx
- docs/src/lib/presenters/FontSize.jsx
- docs/src/lib/presenters/FontWeight.jsx
- docs/src/lib/presenters/LineHeight.jsx
- docs/src/lib/presenters/Shadows.jsx
- docs/src/lib/presenters/Transition.jsx
- docs/src/styles/color.css
- docs/src/styles/shadows.css
This allows to show tokens without deciding for one specific way of
presenting all of them (e.g. in a collection of many different ones).
Unfortunately, ColorItem's swatch is not usable independently and we
want to achieve identical style across tokens and also consistently get the deeplink
functionality, so we reimplement the color swatch.
Bug: [T256024](https://phabricator.wikimedia.org/T256024)
> docs: infer presenter from token name

- docs/src/lib/TokenTable.jsx
- docs/src/styles/token-table.css
Create UX-desired style for referenced tokens in TokenTable.
Unfortunately the specification only happened in chat.
Also replace the "primary value" information and custom style with a
dash because that apparently is more clear.
Bug: [T256024](https://phabricator.wikimedia.org/T256024)
> docs: style referenced tokens

- tokens/properties/alias.json
Visualization helped detect that an incorrect value had been provided for the token border.color.neutral.focus
> correct wrong border color value

- docs/src/lib/presenters/Shadows.css
Changing the height and width of the Shadows element to make it consistent with the Color and Transition presenters in our token documentation pages.
Bug: [T256858](https://phabricator.wikimedia.org/T256858)
> modify width and height of the Shadows presenter

- docs/.eslintrc.json
- docs/package-lock.json
- docs/package.json
- docs/src/lib/TokenPresenter.jsx
- docs/src/lib/TokenTable.jsx
- docs/src/lib/presenters/BorderColor.jsx
- docs/src/lib/presenters/Color.jsx
- docs/src/lib/presenters/Cursor.jsx
- docs/src/lib/presenters/FontFamily.jsx
- docs/src/lib/presenters/FontSize.jsx
- docs/src/lib/presenters/FontWeight.jsx
- docs/src/lib/presenters/LineHeight.jsx
- docs/src/lib/presenters/Shadows.jsx
- docs/src/lib/presenters/Transition.jsx
I set `"react/prop-types": "off"` because I felt that for our non-critical use case [this rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md) was a little too strict.
https://phabricator.wikimedia.org/T257096
> Lint .jsx files

- tokens/README.md
The change request made in the original PR (https://github.com/wmde/wikit/pull/62) was dismissed and apparently this content ended up not making it into the tokens README. Filling in the gaps.
> Incorporate dismissed content

- tokens/.style-dictionary/config.js
- tokens/.style-dictionary/lib.js
- tokens/tests/kebabCase.spec.js
This overrides style-dictionary's own kebab case function to prevent it
from hyphenating parts of the path that contain numbers. For example,
style-dictionary produces the name `font-weight-style-h-1` from path
`[ 'font', 'weight', 'style', 'h1' ]`, but we want it to be
`font-weight-style-h1`.
I added some extra context to what's happening inside style-dictionary in [a comment on the task](https://phabricator.wikimedia.org/T257805#6303508).
> Use custom kebab case function for generating token names

- README.md
With the introduction of a fixed Stprybook port (https://github.com/wmde/wikit/pull/71), the README does not need to say what to click to open storybook, since both localhost and the network url should work.
> Update README for running storybook

- docs/src/lib/TokenTable.jsx
- docs/src/lib/flattenTokenTree.js
A little birdie told me that the [token page for state transitions](https://wmde.github.io/wikit/?path=/docs/design-tokens-transitions-state-transitions--page#transition-interaction-button-focus-property) looked silly after my attempted improvement for avoiding word wraps on token names. I had optimistically slapped `white-space: nowrap;` on the whole table column which looks weird as soon as there are multiple token names.
This change now does what I had intended to do and avoids wrapping for individual token names.
> docs: nowrap only for token names, not the whole column

- docs/src/doc/01_getting_started.stories.mdx
Documenting Vue being external, rather than defining it in the code as it makes no difference - [vue-cli docs](https://cli.vuejs.org/guide/build-targets.html#library)
> Add docs for vue being external to the lib

- vue-components/package-lock.json
- vue-components/package.json
- vue-components/src/components/HelloWorld.vue
- vue-components/stylelint.config.js
This PR installs Stylelint to help us lint our style code (css/scss).
The config follows the docs and uses `stylelint-config-standard` with the only change to use indentation of tabs instead 2 spaces (default).
The plugin `stylelint-use-logical` is used to lint for css logical properties, which we introduced in the parent branch of this PR.
> Install and configure Stylelint

- vue-components/build/postcssWikitScope.js
- vue-components/package-lock.json
- vue-components/package.json
- vue-components/postcss.config.js
- vue-components/tests/unit/build/postcssWikitScope.spec.ts
- vue-components/vue.config.js
* removes the `postcss-prefixwrap` scoping which didn't work as intended due to the lack of a shared root node
* adds the custom postcss plugin which limits the selector scope to `.wikit` elements and elements within `.wikit` elements, effectively applying `.wikit ${selector}, ${selector}.wikit` everywhere, with adjustments for pseudo and attribute selectors
* adds ress via sass-loader's `additionalData`
> Style scoping and style reset

- vue-components/nightwatch.config.js
- vue-components/tests/e2e/custom-commands/openComponentStory.js
- vue-components/tests/e2e/specs/Button.test.js
Adds a custom nightwatch command that "hides" the code that selects the iframe.
> Make browser tests work in composed and single storybooks

- README.md
- docker-compose.browsertests.yml
- vue-components/nightwatch.config.js
- vue-components/package.json
I think this should work well enough for now!
Despite the `depends_on` in the `docker-compose.browsertests.yml` I observed occasional hiccups during the first run of the browser tests when the `browsertests` service is faster its dependencies (`selenium` and `storybook-vue`). This problem seemed to go away once the containers have been started once, i.e. it won't fail again once it successfully ran. TL;DR run it again if it fails for weird reasons once, then it should be fine.
> Dockerize browsertests

- vue-components/nightwatch.config.js
- vue-components/tests/e2e/globals.js
I've seen the tests time out twice already on the `this.waitForElementVisible( '#root' )` in the `openComponentStory` since we enabled them yesterday.
> browser tests: increase timeout from 5s to 20s

- package-lock.json
There are still 17 **high** vulnerabilities and they all come from lerna having this `dot-prop` dependency in multiple packages.
> npm aduit: fix 20 vulnerabilities

- docs/package-lock.json
- docs/package.json
- package.json
- vue-components/package-lock.json
- vue-components/package.json
- vue-components/tests/e2e/custom-commands/openComponentStory.js
After enabling the UI Review and Visual Tests options on Chromatic, it became clear that they don't work on our composed Storybook, whose main stories are the design system tokens.
After discussing this with UX, we agreed that it's more important to leverage the features Chromatic offers on our vue components and not on our design tokens.
This PR moves chromatic from the `docs` package to the `vue-components` package.
:heavy_plus_sign: This means the per-branch generated Chromatic URLs will show only the vue components Storybook. It will enable us to run visual tests and use the UI Review feature.
:heavy_plus_sign: This also means the browser tests no longer need to make a difference between a composed storybook and a local vue components storybook.
:heavy_minus_sign: The downside is that …
> Move Chromatic to run on the vue-components package

- README.md
Since we set up the saucelabs tests to run against the dynamic chromatic url generated on each branch, the README is no longer correct.
> Update README for cross browser tests

- vue-components/nightwatch.config.js
This PR adds one more browser config to our sauce labs tests - Safari on macOS.
> vue-components: Add Safari on macOS to the browser tests config

- tokens/properties/alias.json
- tokens/properties/components/Button.json
- vue-components/src/components/Button.vue
> Apply generic button transitions instead of state-specific ones

- README.md
- tokens/package-lock.json
- tokens/package.json
Run `docker-compose run --rm node lerna run watch --stream` during development to see the effect of changes to the token source files (almost) immediately in both the vue-components and the docs storybook without having to manually run `build:tokens`.
> tokens: add watcher for rebuilding during development

- README.md
- vue-components/nightwatch.config.js
- vue-components/tests/e2e/globals.js
- vue-components/tests/e2e/specs/Button.test.js
This PR introduces logic that sends test info to saucelabs using their API after each test run.
This also adds two badges to the README to display the status of the browser tests.
> vue-components: Pass test status to Saucelabs

- .github/workflows/release.yaml
This is the first step from [T260116](https://phabricator.wikimedia.org/T260116)
This workflow will be triggered when a new release is created on the GitHub repo.
The workflow will publish both the `vue-components` and the`tokens` packages with the same version.
> Create release workflow

- tokens/properties/components/Button.json
- vue-components/src/components/Button.vue
- vue-components/stories/Button.stories.ts
- vue-components/tests/unit/components/Button.spec.ts
neutral stays the same
`progressive` -> `primaryProgressive`
`destructive` -> `primaryDestructive`
This renaming includes the component level tokens, the vue component, the story and the unit tests.
> Rename the types of normal button

- vue-components/stories/Button.stories.ts
Remove the knobs and display button types in the same story.
This increases visual tests coverage significantly.
> Reorder button story to show all types at once

- tokens/package.json
Bug: [T261078](https://phabricator.wikimedia.org/T261078)
Currently both  `npm i @wmde/wikit-vue-components` and `npm i @wmde/wikit-tokens` fail with
```
> @wmde/wikit-tokens@1.0.0 postinstall ../node_modules/@wmde/wikit-tokens
> node build/wikimedia-ui-base
internal/modules/cjs/loader.js:651
throw err;
^
Error: Cannot find module '../node_modules/@wmde/wikit-tokens/build/wikimedia-ui-base'
```
Apparently the build script needs to be executed on `prepare`, rather than on `postinstall`.
I tested the `prepare` script with `npm pack` and then installing it in a test vue repo.
> tokens: Execute build script on prepare, not postinstall

- vue-components/.storybook/main.js
- vue-components/.storybook/preview.ts
- vue-components/package-lock.json
- vue-components/package.json
`@storybook/addon-viewports` allows you to look at stories in different viewports. Said viewports are customizable. I used the ones that come from the addon itself.
`@storybook/addon-backgrounds` allows you to look at stories in different backgrounds. Said backgrounds are customizable. The default ones are just light and dark.
> vue-components: Add more Storybook addons

- docker-compose.yml
It was rightfully pointed out that there is no need to specify the build
file if it equals default Dockerfile.
> docker-compose: rm redundant build file

- tokens/properties/components/Icon.json
- vue-components/package.json
- vue-components/src/components/Icon.vue
- vue-components/src/components/iconProps.ts
- vue-components/stories/Icon.stories.ts
- vue-components/tests/unit/components/Icon.spec.ts
- vue-components/tests/unit/components/__snapshots__/Icon.spec.ts.snap
Split out of #193 to ease review.
This intentionally only includes 2 icons in 3 colors and 2 sizes, because those were the ones that are needed for the TextInput component. The rest of the component is going to be implemented at a later point in time.
Figma spec: https://www.figma.com/file/gi3JYwSUQYhKS0mHwK25cQwi/WiKit?node-id=2510%3A4053
> vue-components: add Icon component

- tokens/properties/components/TextInput.json
Replaced all old padding tokens when possible (we'll carry around those vertical paddings for a bit, since they also depend on the line-height of the "label").
> replace textinput padding by spacing tokens

- docs/src/00-doc/03-create-reusable-components/02_designing_components.stories.mdx
A link to the Accessibility guidelines page in the WMF Style guide has been included in the "Design definition of done" section. Also, a small typo and some style issues have been corrected.
> correct and update design doc

- vue-components/nightwatch.config.js
- vue-components/package.json
- vue-components/tests/e2e/custom-commands/openComponentStory.js
- vue-components/tests/e2e/globals.js
- vue-components/tests/e2e/specs/Button.test.js
We configured the browser tests (on Saucelabs) to run on Safari but that never happened because the npm command was not executing the sauceSafari configuration.
This PR fixes that and attempts to work around a [bug in nightwatch (#2308)](https://github.com/nightwatchjs/nightwatch/issues/2308) involving `waitForElementVisible` in Safari.
> Add sauceSafari to e2e script

- package.json
- tokens/package.json
- vue-components/package.json
The title should maybe read "for all published packages and the root
project" instead but it's cumbersome.
A short research did not yield any information if just putting it in the
root package.json would somehow have lerna take care of distributing it
to the packages but I wanted to be sure the information is part of the
published artifacts.
> use phabricator as a bug tracker for all packages

- vue-components/src/components/TextInput.vue
This caused a build error in the Query Builder code base when loading the TextInput.vue source file.
Interestingly I'm not getting any errors running `docker-compose run --rm node lerna run build --scope @wmde/wikit-vue-components` even before fixing them, but the problems are definitely there. I can't see any major differences between the two (Query Builder and vue-components/ here) build setups. I'd be curious to hear if anyone has an idea why the type checking isn't as strict here.
Phabricator: https://phabricator.wikimedia.org/T264784
> TextInput: fix incorrect typing

- docs/src/00-doc/03-create-reusable-components/03_developing_components.stories.mdx
At the time the original naming conventions were documented, the Button
was the only existing component which only exists of a single element.
While working on the TextInput component in #193 we found this addition
to the naming scheme to work well for us.
> Improve component-level token naming docs

- vue-components/package.json
This PR aims to resolve an issue with the `dist` folder being excluded from our npm package. To validate and reproduce locally, please follow these instructions: https://phabricator.wikimedia.org/T264891#6536974
Once this PR is merged, a release needs to be made to confirm the issue was indeed fixed and fix the bug this PR addresses.
Bug: [T264891](https://phabricator.wikimedia.org/T264891)
> Add prepare script fo vue-components

- .github/workflows/test-and-demo.yaml
- docs/src/00-doc/02_contributing.stories.mdx
- vue-components/nightwatch.config.js
Extract and use the commit hash as the [chromatic permalink](https://www.chromatic.com/docs/permalinks#build-your-own-permalink) for saucelabs to access. This prevents issues with branch names and enables us to name our branches in any way we please.
Related To: [T262270](https://phabricator.wikimedia.org/T262270)
> Use commit hash as chromatic url

- vue-components/package-lock.json
- vue-components/package.json
At the time of writing, storybook 6 was not released yet and running the
`extract` command on a storybook 5 (the npx default) caused an error.
Not sure if pinning to the now-current storybook version would be
better, but it's not how the storybook people document it[1], and will
cause future update effort (or inconsistency) while it is unlikely the
command will ever change without us having to touch the line anyways.
[1]: https://storybook.js.org/docs/vue/workflows/storybook-composition#improve-your-storybook-composition
> vue-components: plain storybook extract command

- vue-components/.storybook/manager.ts
- vue-components/stories/Input.stories.ts
- vue-components/stories/TextInput.stories.ts
- vue-components/stories/ValidationMessage.stories.ts
67c106894ec3f82763a9dd61f2816bfbb3366d91 set a configuration option for
the navigation of the vue components storybook. This option doesn't get
applied for the docs storybook which caused the components' navigation
items not to look as intended in the composed storybook.
(thanks @wiese for spotting that)
^ what it should have looked like
^ what it looked like in composition mode before this patch
> Fix component navigation in composed storybook

- vue-components/package.json
- vue-components/tsconfig.json
Exporting type declaration files with the component library allows us to import its bundled `dist/wikit-vue-components.common.js` file from a TypeScript code base without producing compile-time errors. For now, the types for exported components don't contain any information beyond declaring them as Vue components, i.e. no information about props or slots.
The test files are removed from the tsconfig `include` entry to avoid exporting type declaration files for them. This shouldn't have 
any effect when running the tests.
> vue-components: export .d.ts files

- vue-components/package.json
This allows consuming applications to load components via
`import { Button } from '@wmde/wikit-vue-components';` which is what our
docs already claim to work. The `main` entry that is currently there
(dist/index.js) doesn't exist.
(Sorry, I should've noticed that while reviewing #211.)
I tried this change out in the query builder repo, and it works ~~, but complains about missing type declarations, which I think can be added in a separate change~~.
Added the missing puzzle piece for enabling imports from a TS code base in #223.
> vue-components: fix dist entry point

- docs/src/00-doc/04_release_management.stories.mdx
- package.json
Adds a script to manage versioning when making new releases. This prevents lerna from pushing incorrect tags automatically, and gives developers more control on what is committed with a version bump change.
> Add bump-version script

- vue-components/src/components/Input.vue
- vue-components/src/components/TextInput.vue
This also allows us to bind a value to the Input component via `v-model` which we tripped over while working on #219.
> Input: re-emit input event to allow parents to listen for `@input`

- vue-components/src/components/TextInput.vue
- vue-components/src/components/util/generateUid.ts
- vue-components/tests/unit/components/util/generateUid.spec.ts
Wrapping the label around the input element became questionable as soo
as we also included the validation message in the TextInput component.
We originally went with the label as the root element of the component
to work around having to generate an id for it.
According to the WCAG having the `for`-attribute is also beneficial for
screenreaders:
https://www.w3.org/TR/2008/WD-WCAG20-TECHS-20080430/H44.html
> TextInput: use <label> for the label

- vue-components/src/components/Message.vue
The extra icons were added in #230 (cb1bcb200757564c4ee87a5c115603fa4e3377c7) for [T265582](https://phabricator.wikimedia.org/T265582), so they can now be used in this Message component.
Bug: [T265583](https://phabricator.wikimedia.org/T265583)
> Use correct icons for message types

- tokens/properties/alias.json
This makes available the smallest layout spacing token
> add xxsmall layout token

- tokens/properties/components/LookupMenu.json
- vue-components/nightwatch.config.js
- vue-components/src/components/Lookup.vue
- vue-components/src/components/LookupMenu.vue
- vue-components/stories/Lookup.stories.ts
- vue-components/tests/e2e/specs/Lookup.test.js
- vue-components/tests/unit/components/Lookup.spec.ts
- vue-components/tests/unit/components/LookupMenu.spec.ts
We implemented the "no match found" text with a slot as opposed to a
prop anticipating future requirements to also show markup and/or links
when no results were found.
Bug: [T265010](https://phabricator.wikimedia.org/T265010)
> Lookup: add "no match found" behavior

- tokens/properties/components/LookupMenu.json
- vue-components/nightwatch.config.js
- vue-components/src/components/Input.vue
- vue-components/src/components/Lookup.vue
- vue-components/src/components/LookupMenu.vue
- vue-components/src/components/MenuItem.ts
- vue-components/stories/Lookup.stories.ts
- vue-components/tests/e2e/specs/Lookup.test.js
- vue-components/tests/unit/components/Lookup.spec.ts
- vue-components/tests/unit/components/LookupMenu.spec.ts
This implements the lookup behavior by exposing the Lookup's internal input value through a `.sync`able prop (with a corresponding event), and making the selected item bindable via `v-model`. Naming aside, whether `v-model` binds the internal `<input>` value or the selected item seems to be the choice that has to be made when developing a Lookup component. The latter approach made more sense to me, as it seems more intuitive that the value of such a component is what is selected, not what is typed into the search field.
Bug: [T265012](https://phabricator.wikimedia.org/T265012)
> Lookup behavior

- vue-components/src/components/Lookup.vue
I decided against using `this.$el.querySelector( 'input' )?.blur();` as this error is actually a case of a false positive and I wanted to make that obvious and explicit.
> Disable false positive "could be null" linting error

- vue-components/src/components/Icon.vue
- vue-components/src/components/Message.vue
- vue-components/src/components/iconProps.ts
- vue-components/stories/Icon.stories.ts
- vue-components/tests/unit/components/Icon.spec.ts
An enum seems to be the appropriate data structure for enumerating the valid types of an Icon.
This PR sits on top of #233 to better showcase how those Enums would be used, but it is primarily intended for discussion.
What do you all think? Does using the `enum` data-structure more (like in [Bridge](https://github.com/wikimedia/mediawiki-extensions-Wikibase/tree/master/client/data-bridge/src/definitions)) make sense to you?
> Use TypeScript enums for icon types

- docs/src/00-doc/03-create-reusable-components/03_developing_components.stories.mdx
- tokens/.style-dictionary/config.js
- tokens/.style-dictionary/token-schema.json
Generating a JSON schema describing the structure of token files and including all token names makes it possible for text editors to provide autocompletion in token JSON files. This is especially useful for token references (e.g. `{font.line-height.style.label.value}`) which would otherwise be typed by hand.
Letting the text editor know which JSON files to apply the schema to requires some configuration. I tried it out with VS Code and Intellij.
VS Code has good [documentation](https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings) on getting better editor support for JSON files and working with JSON schemas. TL;DR paste the following into your JSON workspace settings:
```json
{
"json.schemas": [
{
"fileMatch": [
"tokens/properties/**/*.json"
],
"url": …
```
> Improved editor support for token files through JSON schemas generated via style-dictionary

- vue-components/stories/Lookup.stories.ts
- vue-components/stories/LookupMenu.stories.ts
- vue-components/tests/e2e/custom-commands/openComponentStoryDirectory.js
- vue-components/tests/e2e/specs/Lookup.test.js
This will be used for design verification and visual regression testing.
That seems in particular important for possible upcoming refactoring for
this component.
Behavior has to still be evaluated with the actual component.
> Add stories for the internal LookupMenu component

- vue-components/src/components/Button.vue
This makes sure our buttons only contain single-line text, which is recommended from a design standpoint.
> add white-space property to button component

- docs/package-lock.json
- docs/package.json
- lerna.json
- tokens/package-lock.json
- tokens/package.json
- vue-components/package-lock.json
- vue-components/package.json
This pre-release allows using the both Message and the Lookup component in other work-in-progress projects while still finishing up the last aspects of the Lookup component.
The Message should already be done.
https://github.com/wmde/wikit/compare/v1.1.2..alphaLookupAndMessageRelease
> Bump version to 1.2.0-alpha.0

- docs/src/13-animation.mdx
- docs/src/13-animation.stories.mdx
- tokens/properties/alias.json
- tokens/properties/global.json
This makes available global and alias tokens to be used as values for animations' duration and delay properties.
To be decided (please let me know your thoughts) whether we should split duration and delay tokens into separated pages.
> Create animation tokens

- tokens/properties/alias.json
- tokens/properties/components/ValidationMessage.json
this makes inline warning messages bulletproof in terms of contrast agains any backgorund color
> fix contrast of warning text

- vue-components/package-lock.json
- vue-components/package.json
- vue-components/src/components/Lookup.vue
- vue-components/src/components/LookupMenu.vue
- vue-components/stories/Lookup.stories.ts
- vue-components/tests/e2e/specs/Lookup.test.js
+ an event is emitted from Lookup when user scrolls in the LookupMenu that contains the first and last indexes of visible elements
+ added a browser test
> Lookup event emitter on scroll

- .github/workflows/test-and-demo.yaml
- docs/src/00-doc/05-decisions-and-ADRs/adr/0011-visual-testing.stories.mdx
The combined artifact and dependency cache was causing issues while trying to restore it in branches that potentially make changes to the artifacts. In this PR we fix this by splitting the artifact cache (which is required for the proper deployment of storybook in the `deploy` job, from the dependency cache, which is required in all steps).
Issue: [T266460](https://phabricator.wikimedia.org/T266460)
> Fix caching issues

- vue-components/tests/unit/components.spec.ts
The test was added to ensure that all components exhibit the class
"wikit" in their root node in order to be able to have a selector for
styles (resets).
At the time we missed that components may have required props which will
have to be specified to render (mount) the component.
This allows for a quick way to specify those props per component.
However, as this an endless job, I think we may be better off swapping
this jest test for something based on static analysis (e.g. inspired by
[0]). Granted, this can not do the full complexity of a vue component
justice, but we probably don't want dynamic behavior in the wikit class
anyway.
[0]: https://github.com/vuejs/eslint-plugin-vue/blob/80b8983/lib/rules/static-class-names-order.js
> vue-components: check components' wikit class on required props

- tokens/properties/alias.json
The value of font-color-progressive-active should be Accent 30. This is currently an unused token.
> correct wrong font color value

- vue-components/src/components/LookupMenu.vue
@itamargiv  thanks for the help yesterday. we did miss one thing, though.
the focus on the input is lost after selecting an item.
@micgro42 had another approach and it's working with FF and chrome (haven't tested with safari and IE)
> firefox_doesnt_show_active_styles_while_LookupMenu-item_is_clicked

- README.md
The badge broke after renaming the workflow from "Test and deploy" to "Test and Deploy"
> Fix "Test and Deploy" workflow badge

- tokens/package.json
- tokens/properties/global.json
This way, our global tokens are based on the variables contained by the latest version of wikimedia-ui-base whenever possible.
Issue: https://phabricator.wikimedia.org/T263722
> Use latest version of wikimedia-ui-base

- package.json
This PR fixes a problem in #282 Where the tokens are not up to date with the current state of the code. This is done by ensuring that each time the storybook is built, the tokens are built as well, as a prerequisite.
> Ensure tokens are present before building storybook

- vue-components/tests/e2e/specs/Button.test.js
- vue-components/tests/e2e/specs/Lookup.test.js
After discovering that the tests runner was causing chromatic to respond with 503 due to heavy traffic, we decided to try and add a pause between each test, to mitigate the amount of requests.
> Add e2e delay

- tokens/properties/components/LookupMenu.json
- vue-components/src/components/Lookup.vue
- vue-components/src/components/LookupMenu.vue
- vue-components/stories/LookupMenu.stories.ts
This is done in preparation for remaking the LookupMenu in to a more general OptionsMenu that is then to also be used for the Dropdown. And the Dropdown has options who's label is not bold.
Two options and controls are added to the story to showcase this.
Todo:
> Make bold titles in LookupMenu optional

- tokens/properties/alias.json
The value of font-color-progressive-active should be Accent 30 instead of Accent 50.
This is not a dejà vu. I failed to actually replace the color value in the original PR (#272). I only had one job :facepalm:
> Correct value of progressive-active font color

- tokens/properties/components/OptionsMenu.json
- vue-components/src/components/Lookup.vue
- vue-components/src/components/OptionsMenu.vue
- vue-components/stories/OptionsMenu.stories.ts
- vue-components/tests/e2e/specs/Lookup.test.js
- vue-components/tests/unit/components/Lookup.spec.ts
- vue-components/tests/unit/components/OptionsMenu.spec.ts
Builds upon: #282 
Is followed by: #288 
That component is now generic enough to be used both by the Lookup and the Dropdown and so it should have a name that reflects this.
> Rename LookupMenu to OptionsMenu

- CHANGELOG.md
- vue-components/src/components/Dropdown.vue
- vue-components/src/main.ts
- vue-components/stories/Dropdown.stories.ts
- vue-components/tests/unit/components/Dropdown.spec.ts
The `<label>` does not seem to natively focus non-form elements even if they have a `tabindex >= 0` (at least on Firefox), so this is done explicitly via a click event.
The SVG of the small arrow is added inline for now. This allows us to style it with CSS, which wouldn't be possible if we were to use it via background-image. It can be extract if and when we need to use it somewhere else as well. It was not added to the Icon component as that component explicitly sets a color instead of allowing the usage of the current text color.
The scroll events are ignored as a Dropdown always has all its possible options available.
The validation message will be added in another commit.
Bug: [T266545](https://phabricator.wikimedia.org/T266545)
> Add Dropdown component

- vue-components/src/components/Icon.vue
There’s already an eslint-disable earlier in the file, so I assume this one is meant to reenable the rule, now that the inline SVGs are done.
> Fix eslint comment

- vue-components/package-lock.json
- vue-components/package.json
- vue-components/src/components/Lookup.vue
- vue-components/src/components/TextInput.vue
- vue-components/src/compositions/validatable.ts
- vue-components/tests/unit/compositions/validateable.ts
With these being the first meaningful case of code-reuse, it is a good moment to introduce the vue3 composition api via a plugin to this vue2 library.
To get the type inference for the setup option, we have to use the defineComponent function for creating our components. This has the side-effect that we have to rethink how to type the menu ref. The solution was to move this into the setup function as well because there we can use the vue3 way of accessing and _typing_ refs.
The actual validation message will be added to the Dropdown component in a follow-up pull request.
Todo:
Bug: [T266546](https://phabricator.wikimedia.org/T266546)
> Extract validation message logic with composition

- vue-components/src/components/Dropdown.vue
This adds a 12px margin to the left of the expand icon so it's properly separated from the dropdown label.
TBD whether it would be necessary to apply `white-space: nowrap` to the dropdown text in order to prevent unwanted wrapping after this change.
> fix dropdown spacing

- vue-components/src/components/Dropdown.vue
- vue-components/stories/Dropdown.stories.ts
- vue-components/tests/unit/components/Dropdown.spec.ts
The `menuItems` `PropType` is removed from the prop definition as it seems to be completely ignored. However, the menuItem prop must be defined in the signature of the setup function even if it is not used inside the setup function to receive typing in the computed methods added via the usual options API.
Bug: T266546
> Add Error and Warning state to Dropdown

- vue-components/src/components/Button.vue
This referred to an attempt at using the shorter
`Array.prototype.includes.bind( [ 'neutral', 'primaryProgressive', 'primaryDestructive' ] )`
which caused problems at build time.
> vue-components: remove confusing comment

- .github/workflows/test-and-demo.yaml
This PR finally brings back branch hosting for the composed (tokens+docs+vue-components) storybook :tada: 
I haven't found a good way/place to show the netlify link. I added a "Print deploy URL" step in the `deploy` job, which may be good enough for now? `netlify-cli` advertises an `--alias` flag for predictable deployment URLs which looks like a good option to create deployments on a per-branch instead of a per-commit basis so that it can be permanently attached to a PR, but I didn't want to recreate [past problems](https://phabricator.wikimedia.org/T262270) by building the branch name into the URL.
Bug: [T261650](https://phabricator.wikimedia.org/T261650)
> Use netlify for branch hosting the docs storybook

- .github/workflows/test-and-demo.yaml
- vue-components/nightwatch.config.js
Our CI browser tests often fail or time out due to problems with Chromatic and running tests against the storybook preview was arguably abusing the service to begin with. Pointing them at netlify will hopefully result in more stable browser test results.
> Run browser tests against netlify

- tokens/properties/alias.json
- tokens/properties/components/Button.json
- vue-components/src/components/Button.vue
This provides the tokens that will be used to style quiet and icon-only buttons.
> Update button tokens

- CHANGELOG.md
- vue-components/src/components/iconProps.ts
This reuses the color in the css `color` attribute of the parent.
Bug: [T270330](https://phabricator.wikimedia.org/T270330)
> Add a color to have the icon reuse the parent text color

- CHANGELOG.md
- vue-components/src/components/Button.vue
- vue-components/stories/Button.stories.ts
- vue-components/tests/unit/components/Button.spec.ts
We want to support buttons that are of normal variant and progressive type.
Added a method to the updated hook to throw an error if an unsupported combination of variant and type is used by the application. For typing reasons this had to happen inside the Vue3 setup method.
> Restructure Button props

- vue-components/src/components/Button.vue
HTML tags in doc comments aren't pretty, but many IDEs remove trailing
whitespaces automatically.
> Use <br> instead of trailing double-whitespace

- .github/workflows/comment-deploy-url-to-pr.yaml
**Please review #335 first**
This will comment the netlify deploy URL to the PR as soon as it's opened, which makes it more visible than it was before.
The way the URL is being generated is a little adventurous, but it should work as long as our netlify site isn't renamed.
... and ignore the two failed comments by the bot. For future PRs there will only be one comment with a URL that will remain the same (because of #335) even when the PR is updated.
> Comment deploy URL to PR

- vue-components/src/main.ts
To be able to to create the icon-only buttons as they are showcased in Storybook, the consuming application needs access to the Wikit Icon component.
Therefore, it can no longer be an internal component.
> Export Icon component

- vue-components/src/components/Checkbox.vue
Applying min-width (and min-height, just in case) to prevent the checkbox input from shrinking.
Issue: [T272609](https://phabricator.wikimedia.org/T272609) (1)
> Fix checkbox's width

- vue-components/src/components/ToggleButton.vue
- vue-components/src/components/ToggleButtonGroup.vue
- vue-components/src/main.ts
- vue-components/stories/ToggleButton.stories.ts
Works, but not sure if those props make any sense at all
> ToggleButton and ToggleButtonGroup

- docs/.storybook/wikit.js
This PR aims to fix the wikit logo link.
Phabricator: https://phabricator.wikimedia.org/T266326
Bug: T266326
> Fix logo url to link to home page

- vue-components/src/components/Button.vue
- vue-components/src/components/ToggleButton.vue
This PR aims to fix an issue with hover styles by correcting the pseudo selector order to reflect the overrides performed by the user. i.e. an element is:
1. First `:focus`ed (most general case)
2. Then `:hover`ed (specific case before activated, desktop only)
3. And only then potentially `:active`ated
In this case the selector cascade reflects that flow and thus does not require a higher specificity to perform overrides.
See: https://phabricator.wikimedia.org/T266557
Bug: T266557
> Fix pseudo-selector order

- vue-components/src/components/OptionsMenu.vue
- vue-components/tests/unit/components/Dropdown.spec.ts
- vue-components/tests/unit/components/Lookup.spec.ts
Apparently, Chrome is not supporting the options for scrollIntoView.
Therefore we fall back to the basic boolean parameter. This results in a
somewhat more abrupt scroll. That issue can maybe be revisited in future
versions, possibly after support for IE11 has been officially dropped.
Bug: [T272999](https://phabricator.wikimedia.org/T272999)
> fix: keyboard scroll of OptionsMenu not working on Chrome

- .github/workflows/test-and-demo.yaml
The latest release of the paths-filter action 2.9.1 caused a failure of all CI update jobs. This release contained a single PR dorny/paths-filter#74
The error message in all of our CI setup jobs was:
```
Run dorny/paths-filter@v2
with:
filters: visual:
- 'tokens/**'
- 'vue-components/**'
behavioral:
- 'vue-components/**'
token: ***
list-files: none
initial-fetch-depth: 100
Changes will be detected against the branch master
Searching for merge-base master...QuantityInput
/usr/bin/git rev-list --count --all
640
/usr/bin/git merge-base master QuantityInput
fatal: Not a valid object name master
/usr/bin/git fetch --depth=1280 origin master:master QuantityInput
From wmde/wikit
* [new branch]      master     -> master
* branch            QuantityInput -> FETCH_HEAD
/usr/bin/git rev-list --count …
```
> ci: pin paths-filter to previous version to avoid CI failure

- tokens/properties/alias.json
- tokens/properties/components/Button.json
Tiny PR to correct the token applied to define the background color of normal neutral buttons on focus.
> correct bg-color of focused normal neutral buttons

- CHANGELOG.md
- vue-components/src/components/DateInput.vue
- vue-components/src/main.ts
- vue-components/stories/DateInput.stories.ts
- vue-components/tests/unit/components/DateInput.spec.ts
Bug: [T273002](https://phabricator.wikimedia.org/T273002)
> Start DateInput

- vue-components/src/components/Icon.vue
- vue-components/src/components/iconProps.ts
This should allow applying the subtle, emphasized and inverted colors to the icon component.
This is what happens when you keep forgetting that you can run tests locally 🙈
> Add missing color classes and props to icon component

- vue-components/src/components/Popover.vue
Currently, doing any debug shows a lot of these events being emitted
making debugging much harder (and also has performance costs). Let's
just not do it.
> Avoid emitting 'update:isShown' when not needed

- vue-components/src/components/Dropdown.vue
- vue-components/src/components/OptionsMenu.vue
Similar to what ooui has done:
https://doc.wikimedia.org/oojs-ui/master/js/source/DropdownWidget.html#OO-ui-DropdownWidget
This prevents the whole screen to scroll when you use keyboard to
navigate through items.
Bug: T277759
> Add preventDefault to keydown handlers of menu items and dropdown

- vue-components/src/components/Checkbox.vue
- vue-components/src/styles/mixins/Label.scss
This should prevent the words in any label text from breaking arbitrarily whenever their content wraps. Hyphenation is also introduced to prevent creating disproportionate white space between lines when long words are present.
Before:
After:
> Fix label word wrap

- vue-components/src/components/Checkbox.vue
- vue-components/stories/Checkbox.stories.ts
This makes the checkbox input to always be aligned with the first line of text of its label. A checkbox with a longer label was included in the _All_ story  page in order to showcase the changes.
Issue: [T272609](https://phabricator.wikimedia.org/T272609) (Number 4)
> Fix checkbox input alignment

- CHANGELOG.md
- tokens/properties/alias.json
- tokens/properties/components/Button.json
- tokens/properties/components/Checkbox.json
- tokens/properties/components/ToggleButton.json
- vue-components/src/components/ToggleButton.vue
💥 Breaking changes 💥
This applies the right box-shadow (and border) styles to filled elements on focus. Alias tokens were deleted or modified.
Affected components: 
- Primary buttons (progressive & destructive, iconOnly)
- Checkbox
- Toggle button
Issue: [T272626](https://phabricator.wikimedia.org/T272626)
> Correct inset styles of filled components on focus

- vue-components/src/components/Checkbox.vue
This applies the right styles and behavior to the input of unchecked disabled checkboxes. Still, probably the structure of the disabled pseudo-class could be improved? 🤔 
Issue: [T283145](https://phabricator.wikimedia.org/T283145)
> Correct style of unchecked disabled checkbox

- docs/src/00-doc/01_getting_started.stories.mdx
The underscores are not needed when one wants to include *variables.css*.
> Fix docs about path to variables.css

- vue-components/src/components/Dropdown.vue
- vue-components/tests/unit/components/Dropdown.spec.ts
This event listener shouldn’t be called for events bubbling up from the label (including any components in the suffix slot).
Bug: [T277762](https://phabricator.wikimedia.org/T277762)
---
Tested with the following storybook patch:
```diff
diff --git a/vue-components/stories/Popover.stories.ts b/vue-components/stories/Popover.stories.ts
index 24ce522..941aaf4 100644
--- a/vue-components/stories/Popover.stories.ts
+++ b/vue-components/stories/Popover.stories.ts
@@ -1,5 +1,6 @@
import Popover from '@/components/Popover';
import Icon from '@/components/Icon';
+import Dropdown from '@/components/Dropdown';
import Button from '@/components/Button';
import { PopoverPositions } from '@/components/PopoverProps';
import { Component } from 'vue';
@@ -115,3 +116,32 @@ export function all(): Component …
```
> Move Dropdown keydown listener to select element

- vue-components/tests/unit/components/Dropdown.spec.ts
- vue-components/tests/unit/components/LookupCore.spec.ts
- vue-components/tests/unit/components/Popover.spec.ts
The Jest documentation for [Timer Mocks][1] says that this doesn’t happen automatically, and we probably want to clean up timers between tests.
[1]: https://jestjs.io/docs/timer-mocks
> Restore real timers in tests that use fake timers

- .github/workflows/test-and-demo.yaml
Run CI on pull requests, including external ones. To avoid double CI runs, this means we no longer run CI on pushes, except to the master branch (after a pull request was merged). The deploy job is skipped on external pull requests, since the secrets won’t be available; this should cause the browser-tests job to be skipped as well.
Bug: [T283911](https://phabricator.wikimedia.org/T283911)
> ci: run on pull requests

- docs/src/00-doc/03-create-reusable-components/03_developing_components.stories.mdx
We removed the example button browser test because now there are
more browser tests written for other components, therefore we don't
need an example one anymore.
> Update "Developing Components" doc

- tokens/properties/mixins/BouncingDots.json
This change converts a hard-coded calculation value in  the tokens source into a token value, as the hard-coded calculation was generating code that was both unusable in the CSS variable sheets (CSS does not understand `/` without `calc`) and was causing the sass compiler to emit deprecation warnings.
Bug: [T288809](https://phabricator.wikimedia.org/T288809)
> Convert hard coded calculation into a token value

- vue-components/src/components/TextArea.vue
- vue-components/stories/TextArea.stories.ts
- vue-components/tests/unit/components/TextArea.spec.ts
This change introduces the read-only state to the TextArea component, by implementing the Input component's read only tokens.
Bug: [T290151](https://phabricator.wikimedia.org/T290151)
> TextArea: Add read-only state

- vue-components/src/components/TextArea.vue
- vue-components/src/styles/main.scss
- vue-components/src/styles/mixins/InlineProgressBar.scss
- vue-components/stories/TextArea.stories.ts
- vue-components/tests/unit/components/TextArea.spec.ts
This change adds the loading state to the TextArea component. Additionally, an issue where the textarea element was overflowing its container was discovered and fixed.
Bug: [T290151](https://phabricator.wikimedia.org/T290151)
> TextArea: Add loading state

- vue-components/src/components/TextArea.vue
- vue-components/stories/TextArea.stories.ts
- vue-components/tests/unit/components/TextArea.spec.ts
This change enables validation states in the TextArea Component.
Bug: [T290167](https://phabricator.wikimedia.org/T290167)
> Add TextArea warning and error states

- vue-components/src/styles/mixins/InlineProgressBar.scss
Tiny change to reduce the speed of the inline indeterminate loader and get it closer to the [WMF live demo example.](https://di-searchland-2.web.app/)
Related but not a blocker to [T290151](https://phabricator.wikimedia.org/T290151).
> Adjust indeterminate inline loader width to reduce its speed

- vue-components/src/components/Table.vue
- vue-components/src/main.ts
- vue-components/stories/Table.stories.ts
This PR creates a Story for the Table component added in [this commit](https://github.com/wmde/wikit/commit/350677c6d2704db7480cfdf2a619b847a44e61e8).
Bug: [T291077](https://phabricator.wikimedia.org/T291077)
> Add Table Story

- CHANGELOG.md
- docs/package-lock.json
- docs/package.json
- lerna.json
- tokens/package-lock.json
- tokens/package.json
- vue-components/package-lock.json
- vue-components/package.json
This change adds the table component to the change log, and bumps the prerelease version to `2.1.0-alpha.4`.
Bug: [T291078](https://phabricator.wikimedia.org/T291078)
> Pre release v2.1.0 alpha.4

- vue-components/src/components/Link.vue
💥 Breaking changes 💥
The current wikit-Link component overflows its container by default. Instead of overriding this behavior in context, we decided to let links wrap.
> Wrap link to prevent overflow

- tokens/properties/alias.json
- tokens/properties/components/Dialog.json
A couple of fixes needed to be applied to the Dialog tokens file:
1. The value of `box-shadow-divider-bottom` was corrected, which means that `$wikit-Dialog-header-box-shadow` can now be applied to the Dialog's header (as intended) instead of to the body.
2. The missing token `$wikit-Dialog-border-color` was created: it should replace the alias `$border-color-base-subtle` being used to style the component at the moment.
> Fix wikit-Dialog tokens

- tokens/properties/components/Table.json
- vue-components/src/components/Table.vue
This aligns the wikit-Table's header text at the top in order to improve readability whenever any of the heading wraps into two or more lines.
> Top-align table headings

- vue-components/src/components/Dialog.vue
- vue-components/stories/Dialog.stories.ts
Bug: [T295875](https://phabricator.wikimedia.org/T295875)
> Add Story & Storybook Documentation for Dialog Component

- vue-components/src/components/Dialog.vue
- vue-components/stories/Dialog.stories.ts
This change fixes several issues with the Dialog component, and it's story:
1. The Dialog overlay did not cover the whole viewport/iframe - This was due to some copying and pasting error where the positioning of the dialog within the viewport was reverted from 50%, 50% (x, y) to 0, 0; and a transform was introduced to try and compensate for it. To fix, the transform was removed and the original positioning values restored.
2. The Scrollbars were not restored in storybook, while navigating from the dialog story when the dialog was still open - This was actually two separate issues:
A. The dialog itself did not complete the hiding animation, and thus the `_restoreScroll` method was not called. This was mitigated by adding a direct call to `_restoreScroll` to the `beforeDestroy` lifecycle …
> Dialog fixes

- CHANGELOG.md
- docs/package-lock.json
- docs/package.json
- lerna.json
- tokens/package-lock.json
- tokens/package.json
- vue-components/package-lock.json
- vue-components/package.json
This change prepares WiKit for the v2.1.0-alpha.8 pre-release.
Bug: [T295877](https://phabricator.wikimedia.org/T295877)
> Bump version to v2.1.0-alpha.8

- docs/package-lock.json
- docs/package.json
- lerna.json
- tokens/package-lock.json
- tokens/package.json
- vue-components/package-lock.json
- vue-components/package.json
- vue-components/src/main.ts
This change bumps the pre-release version of WiKit, this time also exporting the Dialog component from `main.ts`.
> Export dialog component

- vue-components/tests/unit/components/Dialog.spec.ts
The tests are now described in [T295876](https://phabricator.wikimedia.org/T295876)
> Remove specs for browser tests

- vue-components/src/components/Dropdown.vue
- vue-components/tests/unit/components/Dropdown.spec.ts
This prevents the wikit-Dropdown component from emitting an 'input' event in case users click the selected option from the menu again.
Issue: [T298020](https://phabricator.wikimedia.org/T298020)
> Prevent dropdown from emitting an 'input' event if the selected option is selected again

- vue-components/stories/Dialog.stories.ts
Phab Task: https://phabricator.wikimedia.org/T298238
IE11 does not support es6 syntax. function adjusted to traditional js seems
> revert arrow function to traditional js to support IE11

- vue-components/README.md
- vue-components/package.json
- vue-components/src/components/Button.vue
- vue-components/src/components/Input.vue
- vue-components/src/components/Table.vue
- vue-components/vue.config.js
This adds an extra build to dist, named `wikit-vue-components-vue3compat`, which includes some changes to make Wikit compatible with the Vue 3 migration build:
- the `@vue/composition-api` dependency is externalized, because it’s incompatible with Vue 3
- components that use an HTML element with the same name (e.g. `Button`/`<button>`) internally use a non-conflicting name (but are still imported and used under their original name elsewhere), because otherwise there are sometimes infinite loops when mounting them
The intention is that this additional build can be used in two ways:
1. with Vue 2, where `vue` is `vue@^2` and `@vue/composition-api` is `@vue/composition-api@^1`
2. with Vue 3, where `vue` is `@vue/compat@^3` and `@vue/composition-api` is an alias for the same module
Note that …
> Add additional build for Vue 3 compatibility mode

- vue-components/.browserslistrc
- vue-components/nightwatch.config.js
- vue-components/package.json
This branch is going to target Vue 3 which no longer support IE11 and
Safari older than 10. See also wikimedia/browserslist-config-wikimedia#6
This should make future builds more robust and slightly faster.
Bug: T301155
> Stop building and testing for IE11

- vue-components/src/components/TextInput.vue
- vue-components/stories/TextInput.stories.ts
This cherry-picks 61d8e32d that was merged in #538
> This allows setting attributes such as required or maxlength or name.
> Cherry pick "Apply extra attributes"

- vue-components/package-lock.json
- vue-components/package.json
- vue-components/stylelint.config.js
The original stylelint-use-logical seems to be effectively unmaintained, and is causing problems with its old stylelint peer dependency; its fork stylelint-use-logical-spec seems reasonably active, has a comparable number of downloads, and is compatible with newer stylelint.
The new version also complains about width/height (wanting them replaced with inline/block-size), but at least one of these replacements is not trivial (in OptionsMenu, the max-width involves the vw unit), so disable this for now.
---
Inspired by 55169482695961c64aa5ceef2a1b7252a398c291 from #543.
> Replace stylelint-use-logical with stylelint-use-logical-spec

- vue-components/.eslintrc.js
- vue-components/package-lock.json
- vue-components/package.json
- vue-components/src/components/Breakpoint.ts
- vue-components/src/components/ResizeLimit.ts
- vue-components/src/components/iconProps.ts
Split out from #548 
This now also makes use of the Microsoft patch to eslint to work around the same problem already encountered previously in wmde/new-lexeme-special-page#74
Bug: T301155
> Upgrade eslint config and suppress reported false-positive errors

- vue-components/package-lock.json
- vue-components/package.json
This uses our fork until wiese/eslint-plugin-vue-root-class#5 is merged and a new version is released. This is needed as preparation for the upgrade to Eslint 8 and Vue 3
> Bump eslint config vue-root-class

- vue-components/src/components/OptionsMenu.vue
- vue-components/src/components/TextInput.vue
The `any` used for the `extraStyles` prop does not actually cause an
error when omitted and building wikit. However it does show up in
VSCode, probably because VSCode uses Volar internally which uses a more
advanced parser for vue files than @vue/cli. Still, it is unclear what
the right way forward here would be. So far, it seemed to not be
possible to type it as `StyleValue`, but maybe I just didn't find the
right place for it.
> Replace `any` types in production code

- CHANGELOG.md
- docs/package-lock.json
- docs/package.json
- lerna.json
- tokens/package-lock.json
- tokens/package.json
- vue-components/package-lock.json
- vue-components/package.json
As part of [#T303503](https://github.com/wmde/wikit/pull/557) we would like to use a Vue3 version of some of the Wikit components, created in the next branch.
> Bump premajor version to v3.0.0-alpha.0

- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
These workflows failed with the error "npm ERR! fsevents not accessible from chokidar". On potential source of this error could be the node version mismatch between `.nvmrc` and the CI action.
> Use node 16 in CI also for the release and prerelease workflows

- vue-components/src/components/TextInput.vue
All the other components (that haven’t been removed in this branch) already have the right `emits`, as far as I can tell.
> Add missing `emits` to TextInput

- vue-components/src/components/Button.vue
- vue-components/src/components/Icon.vue
- vue-components/src/components/Input.vue
- vue-components/src/components/Lookup.vue
- vue-components/src/components/LookupInput.vue
- vue-components/src/components/Message.vue
- vue-components/src/components/OptionsMenu.vue
- vue-components/src/components/TextInput.vue
- vue-components/src/components/ValidationMessage.vue
This should have no effect when running under pure Vue 3, and reduce surprises when using the migration build.
> Add compatConfig: { MODE: 3 } to components

- vue-components/tests/unit/components/Icon.spec.ts
- vue-components/tests/unit/components/__snapshots__/Icon.spec.ts.snap
This ensures that we test all the icon types for changes to the markup, not merely the ones where someone happened to add an explicit test case.
---
The three separate commits might make reviewing slightly easier (though I can’t think of a Git tool that would easily validate that commit 2 only reorders lines when the blocks also share so many lines), but are intended to be squashed for merging.
> Generate Icon snapshot test cases using .each()

- vue-components/src/components/Icon.vue
All <svg> elements shared five common attributes, which can be extracted
into a common object using v-bind – except that the Search type didn’t
have a fill=none attribute before. I assume this wasn’t intentional (or
at least, there’s no discussion of it in #371), so it should be okay to
add the attribute with this change. (There’s no snapshot to update for
this case because there’s no snapshot specifically for the Search type.)
> Cherry Pick "Extract common Icon <svg> attributes (#577)"

- vue-components/tests/unit/components/Icon.spec.ts
- vue-components/tests/unit/components/__snapshots__/Icon.spec.ts.snap
This ensures that we test all the icon types for changes to the markup, not merely the ones where someone happened to add an explicit test case.
> Cherry pick "Generate Icon snapshot test cases using .each() (#578)"

- vue-components/src/components/Button.vue
Firefox allows a button to be `:disabled` and still have `:focus`, if it was programmatically disabled while focused. In this case, the `:focus` styles would beat the `:disabled` styles, since they have higher specificity; we want disabled buttons to always look disabled, though, so wrap all the other styles in `:enabled` so they only apply when wanted.
Bug: T304511
---
Try it out in #586 ([story](https://21112ed285c28145538a4a8bea9cbab88c2bedb9--wmde-wikit.netlify.app/?path=/story/vue_button--self-disabling-button), behavior without this fix) and #585 ([story](https://79baed873074bfcc111a4b7587f067fe2fdba29e--wmde-wikit.netlify.app/?path=/story/vue_button--self-disabling-button), with fix).
> Wrap button :focus, :hover and :active styles in :enabled

- vue-components/src/components/Button.vue
Firefox allows a button to be :disabled and still have :focus, if it was
programmatically disabled while focused. In this case, the :focus styles
would beat the :disabled styles, since they have higher specificity; we
want disabled buttons to always look disabled, though, so wrap all the
other styles in :enabled so they only apply when wanted.
The stylelint rule max-nesting-depth (max depth: 3), which complains
about the change, is disabled – the alternative solutions (combining
selectors together) seem worse to us in this case.
Bug: T304511
> Cherry pick "Wrap button :focus, :hover and :active styles in :enabled (#584)"

- docs/package-lock.json
- docs/package.json
@storybook/html requires React 16 (though many other storybook packages are compatible with 16 || 17 || 18), and having multiple React versions in the tree seems to cause issues.
The explicit react-is dependency can be removed from package.json, we don’t use it directly. (It’s still pulled in by other packages.)
> docs: Use React 16 instead of 17

- docs/.storybook/main.js
- docs/package.json
--static-dir (-s) is deprecated since Storybook 6.4 [1].
[1]: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
> Update docs/ Storybook config

- vue-components/src/components/Lookup.vue
- vue-components/src/components/LookupInput.vue
- vue-components/src/components/OptionsMenu.vue
- vue-components/tests/a11y/AllComponents.spec.ts
Add more specific and complete aria attributes to allow screen
readers to announce menu and menu items correctly.
TODO:
- add role alert in a way that it is read by screen readers every time the 'no-results' panel is shown. the default behavior is that it is read only once if the text remains the same. This issue will be addressed in a follow-up PR.
Bug: [T290733](https://phabricator.wikimedia.org/T290733)
> Add aria attributes for screen readers

- vue-components/src/components/Link.vue
- vue-components/src/styles/main.scss
- vue-components/src/styles/mixins/Link.scss
- vue-components/stories/Link.stories.ts
This is needed for the help-link to the spelling variant input
Bug: T298146
> Migrate Link component to the next branch

- vue-components/src/components/Lookup.vue
- vue-components/src/components/LookupInput.vue
- vue-components/src/components/OptionsMenu.vue
- vue-components/tests/a11y/AllComponents.spec.ts
Add more specific and complete aria attributes to allow screen
readers to announce menu and menu items correctly.
Note: adding an alert role that is read by screen readers every time the 'no-results' panel is shown is not implemented in this PR. the default behavior is that it is read only once if the text remains the same. This issue will be addressed in a follow-up PR.
Bug: T290733
> Cherry pick "Add aria attributes for screen readers (#587)"

- docs/package-lock.json
- docs/package.json
- lerna.json
- tokens/package-lock.json
- tokens/package.json
- vue-components/package-lock.json
- vue-components/package.json
npm run bump-version prerelease
Bug: [T290733](https://phabricator.wikimedia.org/T290733)
> Bump version to 3.0.0-alpha.5 (but properly)

- vue-components/src/components/OptionsMenu.vue
Children of an element with a `role="listbox"` should have a
`role="option"`.
See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role
This resulted in an error in the cypress a11y check:
```
NewLexemeForm
1 accessibility violation was detected
┌─────────┬──────────────────────────┬────────────┬────────────────────────────────────────────────────────────────────────────┬───────┐
│ (index) │            id            │   impact   │                                description                                 │ nodes │
├─────────┼──────────────────────────┼────────────┼────────────────────────────────────────────────────────────────────────────┼───────┤
│    0    │ 'aria-required-children' │ 'critical' │ 'Ensures elements with an ARIA role that require child roles …
```
> Fix missing role on no-results slot

- vue-components/src/components/OptionsMenu.vue
Follow-up to #587 and #599 respectively
Children of an element with a `role="listbox"` should have a
`role="option"`.
See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role
This resulted in an error in the cypress a11y check:
```
NewLexemeForm
1 accessibility violation was detected
┌─────────┬──────────────────────────┬────────────┬────────────────────────────────────────────────────────────────────────────┬───────┐
│ (index) │            id            │   impact   │                                description                                 │ nodes │
├─────────┼──────────────────────────┼────────────┼────────────────────────────────────────────────────────────────────────────┼───────┤
│    0    │ 'aria-required-children' │ 'critical' │ 'Ensures elements …
```
> Cherry pick "Fix missing role on no-results slot (#602)"

- vue-components/src/components/Lookup.vue
- vue-components/src/components/LookupInput.vue
- vue-components/tests/unit/components/Lookup.spec.ts
- vue-components/tests/unit/components/LookupCore.spec.ts
We want to add this attribute to lookups on the new lexeme special page, and adding it to the surrounding `<div>` isn’t enough.
Bug: T313891
> Add aria-required attribute to Lookup, LookupInput

- vue-components/src/components/TextArea.vue
This is reusing the corresponding Input token, like we did with all other TextArea properties.
Related issue: [T312633](https://phabricator.wikimedia.org/T312633)
> Apply full opacity to TextArea's placeholder

- vue-components/src/components/Lookup.vue
- vue-components/tests/unit/components/Lookup.spec.ts
Now aria-required can also be handled by this attribute inheritance and no longer needs its own dedicated prop.
Bug: T322686
> Let extra Lookup attributes fall trough to the <input> (#641)

- .github/workflows/test-and-demo.yaml
Bug: T322548
[This PR is tested here: https://github.com/wmde/wikit/actions/runs/3800613650/jobs/6464277983](https://github.com/wmde/wikit/actions/runs/3800613650/jobs/6464277983#step:7:7)
> Replace set-output with $GITHUB_ENV in test-and-demo workflow

- .github/workflows/document.yaml
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
- .github/workflows/test-and-demo.yaml
This takes care of the following warning appearing in our GitHub CI:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, dorny/paths-filter@v2.9.0, actions/setup-node@v1, actions/cache@v2
```
It also removes all of the remaining warnings of the type:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
and
```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to …
```
> Update actions to versions no longer using Node 12

- .github/workflows/comment-deploy-url-to-pr.yaml
- .github/workflows/document.yaml
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
- .github/workflows/test-and-demo.yaml
This collects the changes of the PRs #643, #665 and #666
Bug: T322548
> Cherry Pick commits to fix warnings on GitHub Action

- vue-components/src/components/LookupInput.vue
This should be set to the same ID as the `aria-owns` attribute: the input is not only a functional parent of the options menu (`aria-owns`), but also controls its contents and presence (`aria-controls`).
Bug: T326681
> Add aria-controls attribute to LookupInput

- vue-components/src/components/LookupInput.vue
This should be set to the same ID as the aria-owns attribute: the input is not only a functional parent of the options menu (aria-owns), but also controls its contents and presence (aria-controls).
Bug: T326681
> Cherry-pick 'Add aria-controls attribute to LookupInput (#674)'

- vue-components/src/components/OptionsMenu.vue
Note: this is not reproducible in Wikit, please reproduce in special-new-lexeme. Instructions in the phabricator ticket.
Bug: [T325822](https://phabricator.wikimedia.org/T325822)
> Fix Lookup component scrollbar height after open and closing menu

- .github/workflows/test-and-demo.yaml
- vue-components/package-lock.json
- vue-components/package.json
This does three things:
1. it makes sure we explicitly use _our_ lerna, not the global one that seems to come with `ubuntu_latest` in the build step
2. it makes sure we use the storybook CLI that matches our storybook version when extracting the stories, `npx sb` would install the latest version if it is not already in node_modules
3. it updates chromatic because there was an issue with the chromatic part failing despite a change already being accept in the chromatic web interface (this PR does not touch components at all)
> Fix CI for PRs on master

- .github/workflows/test-and-demo.yaml
- vue-components/package-lock.json
- vue-components/package.json
This is the equivalent of #688 for the `next` branch. However, here we do not need the chromatic update, because we're already on Chromatic v6.
> Fix CI for PRs on next

- .github/workflows/document.yaml
If that is not explicitly set, CI will use whatever comes with `ubuntu_latest` and that is not what we want for this workflow. Node 14 is consistent with what is used in the other workflows. The PR to upgrade these is #684.
This should be merged after #688 and make CI green again on merged branches.
> Explicitly use consistent node version in post-merge workflow

- .github/workflows/test-and-demo.yaml
When this action runs, `hashFiles('*/dist')` would always return the empty string, because it does not match any files. That means that the cache key would always be identical: `linux-`.
This should be merged after #688
> Fix cache key for artifact caching

- docs/src/00-doc/01_getting_started.stories.mdx
With Wikit no longer being actively maintained, its documentation (in https://wmde.github.io/wikit) should be updated to notify any readers that Wikit is deprecated and that it has been superseded by Codex.
Bug: T382052
> Mark Wikit as deprecated in docs
